global: 
  scrape_interval:  5s 
scrape_configs: 
  - job_name:  'django_app' 
    metrics_path:  '/prometheus/metrics' 
    static_configs: 
      - targets: ["host.docker.internal:8000"]
      # - targets: ['localhost:8000']