# Generated by Django 4.1 on 2025-03-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_user', models.IntegerField(verbose_name='Кол-во пользователей')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
    ]
