# Generated by Django 4.1 on 2024-11-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание книги')),
                ('author', models.CharField(max_length=256, verbose_name='Автор книги')),
                ('genre', models.CharField(max_length=256, verbose_name='Жанр книги')),
                ('publication_year', models.IntegerField(verbose_name='Год публикации')),
                ('is_read', models.BooleanField(verbose_name='Прочитана ли книга?')),
                ('img', models.CharField(blank=True, max_length=1024, null=True, verbose_name='URL адресс на обложку книги')),
            ],
        ),
    ]
