# Generated by Django 4.1 on 2024-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_create_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитана ли книга?'),
        ),
    ]
