# Generated by Django 4.1 on 2024-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(blank=True, to='marketplace.feedback', verbose_name='Отзыв'),
        ),
    ]
